spring:
  config:
    import: configs/application-database.yml

server:
  port: 8080


application:
  storage:
    location: /home/maksym/Programming/Java/restapp/src/main/resources/storage/
    max-file-size: 10000000

  security:
    admin:
      username: root
      password: 123456
