version: "3.9"
services:
#  mariadb:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123
      MARIADB_DATABASE: restapp
      MARIDB_USER: user
      MARIADB_PASSWORD: 123456
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"