spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/restapp
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database: mariadb
    properties:
      hibernate:
        format_sql: true
